### ISSUE TITLE
node-red-contrib-alarm-manager v1.1.2

### ISSUE THREAD

**Issue by marc965** [gemini86/node-red-contrib-alarm-manager#1] opened 2024-01-12 16:55 UTC
Hi.

I am just trying out your Alarm-Manager.
It is exactly what i need to manage several alarm conditions in future.
I began to send email notifications and analyzing debug nodes.

I am first using your exampke flow [example_flow.json) and its working.

BUT:
Do you have any explanation why the emitter (output 1: alarms) is sending multiple messages at once (with same content)?
Your example mentioned above Its exacly sending all messages 4 times, the "new alarm" messages, the "cleared alamrs" etc.

Any suggestions what i am doing wrong here?
I am using node-red v3.1.0 on RPi4 any dont have any other problems yet...

Any help very appreciated.
Thanks in advance.

Ciao
Marc

PS: i just tried the other outputs: same issue as output 1.

**Comment by gemini86** [comment] 2024-01-12 18:19
Hello,

Could you please post your flow here so I can try to duplicate? Which V of alarm-manager?
Thanks

**Comment by marc965** [comment] 2024-01-12 19:48
> Hello,
> 
> Could you please post your flow here so I can try to duplicate? Which V of alarm-manager? Thanks

[testflow.json](https://github.com/gemini86/node-red-contrib-alarm-manager/files/13923370/testflow.json)
I am using the newest version 1.1.2

This is your example published on github. Nothing changed.
I only connect email out node or debug node.

**Comment by gemini86** [comment] 2024-01-12 20:04
Thank you.

After installing Alarm-Manager fresh on one of my servers (running node-RED V3.1.0) and importing the flow, I'm not able to reproduce this. I'm only seeing one message per alarm and then the repeating persistent alarm which is configured in the alarm-manager config node. Could you double check your config nodes for duplicates of the alarm-manager node? Should just be the one, which is named "manager 1" in this flow example.

**Comment by marc965** [comment] 2024-01-12 21:46
> Thank you.
> 
> After installing Alarm-Manager fresh on one of my servers (running node-RED V3.1.0) and importing the flow, I'm not able to reproduce this. I'm only seeing one message per alarm and then the repeating persistent alarm which is configured in the alarm-manager config node. Could you double check your config nodes for duplicates of the alarm-manager node? Should just be the one, which is named "manager 1" in this flow example.

**Comment by marc965** [comment] 2024-01-12 21:47
I am so confused!
Dont change anything at your flow!

I cleared last alarm but one alarm still circulating, sending twice!
Send you some Screenshot

![2024-01-12 22_43_35-Window](https://github.com/gemini86/node-red-contrib-alarm-manager/assets/85791333/312d78a7-54ba-4c3e-8ac0-c0f584acf63b)
![2024-01-12 22_45_17-Window](https://github.com/gemini86/node-red-contrib-alarm-manager/assets/85791333/e450ee0e-fda4-4e8e-bce5-61ee60b68014)

**Comment by marc965** [comment] 2024-01-12 21:50
It sseems the alarm is generated twice because i deploy the flow several times...
Is that possible?

**Comment by marc965** [comment] 2024-01-12 21:56
Its impossible for me to stop the last alarm generated, its still circulating. Cant clear it with an imput within limit or a set msg.reset!

**Comment by marc965** [comment] 2024-01-12 22:01
I tried a while: i think this is happening when i am changing the resend intervall and redeploying the flow. This creates several alarms of the same category.

**Comment by marc965** [comment] 2024-01-12 22:04
i have three alarms of the same category now: the third is shown several seconds later because i changed the resend interval.
![2024-01-12 23_02_57-Window](https://github.com/gemini86/node-red-contrib-alarm-manager/assets/85791333/791e46aa-aba5-4b87-9f74-2cd25c4d4e49)

**Comment by marc965** [comment] 2024-01-12 22:05
can you reproduce this?

**Comment by marc965** [comment] 2024-01-12 22:16
I just delete your alarm manager example and reinstall it. Same issue:
When i am generating an alarm (example: high alarm condition) all works fine.

When i dont clear this alarm and go to the "manager 1" properties and change "resend on interval" to 0.5 this happens again...

**Comment by gemini86** [comment] 2024-01-19 14:24
I have tried on 3 different devices running 3.0.1 and cannot reproduce. I recommend stopping node-red and restarting or rebooting your device. It sounds like you have multiple instances of the underlying alarm-monitor node (which is a config node, it's not in the pallet).

Maybe also try creating a new alarm-monitor node:
<img width="389" alt="image" src="https://github.com/gemini86/node-red-contrib-alarm-manager/assets/38013323/0a2b40f2-da69-498e-a814-cf121e761c46">
and then switching all other nodes to point to this, see if this behavior stops.

I'd also see if the msg._id is the same on all duplicate messages.

You may be experiencing some node-red installation issues, try running the install script again:
`bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)`

I will leave this open for a while for others to see and possibly chime in, but I cannot reproduce your issue.

**Comment by marc965** [comment] 2024-01-21 17:25
Hi!
Thank you very much for dealing with my problem.
Usually the Alam-Manager ist working very fine. Love it.

Only when i am changing the  "Resend on interval (minutes)" value this effect (multiple alarms are generated and cant be cleared) is reproducable at each time. To stop this i had to reboot my node-red server.

Then all is working again, my changed value "Resend on interval" is taken into account.
Perhaps its somewhere a missing initializing and two instances are generated - dont know.

If you have an idea feel free to contact me - i can make some tests...

Ciao  Marc

**Comment by gemini86** [comment] 2024-01-21 17:31
This is helpful information. I will try to reproduce this issue and get
back to you ASAP.

**Comment by gemini86** [comment] 2024-01-29 22:46
@marc965 I have located the issue, and am working on a fix. I will notify you when an update is pushed to NPM and will marked this issue as closed.

**Comment by gemini86** [comment] 2024-01-29 23:24
This issue is fixed in v1.1.4. Note that the persistence hook will need to be used to inject any held alarms after changes are made to the alarm manager configuration (eg. changing the resend interval or delay time after alarms have been sent to the alarm-manager). The persistence hook is meant to enable alarms to be loaded after restarts and flow deployment.

**Closed as completed by gemini86** 2024-01-29 23:24 UTC
